"""
Eigene Threat-Intel aus dem Verlauf.

* YARA-Regel je Cluster (IOC-Graph): aus den IOCs, die die Dateien des Clusters
  TEILEN, plus gemeinsamem Imphash. Die Regel entsteht allein aus den
  gespeicherten Befunden – die Originaldateien werden nicht erneut geöffnet.
* Rückwärtstest gegen den gesamten Verlauf: wie viele Dateien im / außerhalb des
  Clusters würde die Regel treffen? (Simulation über die gespeicherten IOCs.)
* Aktivieren = Regel nach data/yara_generated/ schreiben → der YARA-Analysator
  (und damit auch der Watch-Folder) nutzt sie ab der nächsten Datei.
* Export: STIX 2.1 Bundle, MISP-Event (JSON), CSV.
"""
import csv
import datetime
import json
import re
import uuid
from pathlib import Path

from config.settings import APP_CODENAME, APP_VERSION, DATA_DIR

GENERATED_DIR = DATA_DIR / "yara_generated"
RULE_TYPES = ("domain", "ipv4", "email", "onion", "btc", "xmr", "unc_path")
_NS = uuid.UUID("6f2b1c1e-5e3a-4d1b-9a55-5e7e1e0f4a11")          # für stabile STIX-IDs


def _yara_str(v):
    return v.replace("\\", "\\\\").replace('"', '\\"')


def _rule_name(text):
    n = re.sub(r"[^A-Za-z0-9_]", "_", text).strip("_")
    return ("SENTINEL_GEN_" + n)[:120]


def _cluster_facts(db, graph, cluster):
    files = [graph["files"][s] for s in cluster["files"]]
    iocs = [i for i in graph["iocs"] if i["key"] in set(cluster["iocs"]) and i["type"] in RULE_TYPES]
    imps = {}
    for f in files:
        fp = db.fingerprints_for(f["id"])
        if fp.get("imphash"):
            imps.setdefault(fp["imphash"], []).append(f["name"])
    shared_imp = [h for h, names in imps.items() if len(names) >= 2]
    return files, iocs, shared_imp


def cluster_rule(db, graph, cluster, name=None):
    """→ {'name', 'text', 'iocs', 'imphashes', 'threshold'} oder None, wenn nichts Belastbares da ist."""
    files, iocs, imps = _cluster_facts(db, graph, cluster)
    if not iocs and not imps:
        return None
    rname = _rule_name(name or f"{cluster.get('name', 'cluster')}_{datetime.date.today():%Y%m%d}")
    threshold = _tune_threshold(db, iocs, imps, {f["sha256"] for f in files})
    lines = ['import "pe"', "", f"rule {rname}", "{", "    meta:",
             f'        description = "Generated by {APP_CODENAME} from {len(files)} related files '
             f'({len(iocs)} shared IOCs)"',
             f'        author = "{APP_CODENAME} {APP_VERSION}"',
             f'        date = "{datetime.date.today().isoformat()}"',
             '        severity = "high"',
             f'        files = "{_yara_str(", ".join(f["name"] for f in files)[:400])}"']
    if iocs:
        lines.append("    strings:")
        for n, i in enumerate(iocs[:40]):
            lines.append(f'        $ioc{n} = "{_yara_str(i["value"])}" ascii wide nocase   // {i["type"]}')
    conds = []
    if iocs:
        conds.append(f"{min(threshold, len(iocs))} of ($ioc*)")
    for h in imps:
        conds.append(f'pe.imphash() == "{h}"')
    lines += ["    condition:", "        " + " or ".join(conds), "}", ""]
    return {"name": rname, "text": "\n".join(lines), "iocs": [i["value"] for i in iocs[:40]],
            "imphashes": imps, "threshold": min(threshold, len(iocs)) if iocs else 0,
            "cluster_files": [f["sha256"] for f in files]}


def _tune_threshold(db, iocs, imps, cluster):
    """Schwelle „N of ($ioc*)“ per Rückwärtstest: volle Cluster-Abdeckung ohne Fremdtreffer, möglichst streng."""
    if len(iocs) <= 1:
        return 1
    best, best_val = 1, None
    for t in range(min(len(iocs), 4), 0, -1):
        bt = backtest(db, {"iocs": [i["value"] for i in iocs], "imphashes": imps, "threshold": t,
                           "cluster_files": list(cluster)})
        val = len(bt["inside"]) - 3 * len(bt["outside"])
        if len(bt["inside"]) == len(cluster) and not bt["outside"]:
            return t
        if best_val is None or val > best_val:
            best, best_val = t, val
    return best


def compile_check(text):
    """→ None wenn OK, sonst Fehlermeldung (yara nicht installiert → None, Hinweis im UI)."""
    try:
        import yara
    except ImportError:
        return None
    try:
        yara.compile(source=text)
        return None
    except yara.Error as e:
        return str(e)


def backtest(db, rule):
    """Simuliert die Regel über alle gespeicherten Analysen (IOCs + Imphash)."""
    want = {v.lower() for v in rule["iocs"]}
    imps = set(rule["imphashes"])
    inside, outside = [], []
    cluster = set(rule["cluster_files"])
    seen = set()
    for row in db.list_analyses(limit=100000):
        if row["sha256"] in seen:
            continue
        seen.add(row["sha256"])
        vals = {r["value"].lower() for r in db.iocs_for(row["id"])}
        hits = sum(1 for w in want if any(w in v for v in vals))
        fp = db.fingerprints_for(row["id"])
        match = (rule["threshold"] and hits >= rule["threshold"]) or (fp.get("imphash") in imps)
        if match:
            (inside if row["sha256"] in cluster else outside).append(row)
    return {"inside": inside, "outside": outside, "cluster_size": len(cluster)}


def activate(rule, directory=None):
    d = Path(directory or GENERATED_DIR)
    d.mkdir(parents=True, exist_ok=True)
    path = d / f"{rule['name']}.yar"
    path.write_text(rule["text"], encoding="utf-8")
    return path


def generated_rules(directory=None):
    d = Path(directory or GENERATED_DIR)
    return sorted(d.glob("*.yar")) if d.is_dir() else []


# ── Export ───────────────────────────────────────────────────────────────────
def collect(db, case_id=None, min_level="ELEVATED", graph=None, cluster=None):
    """IOCs + Datei-Hashes eines Scopes (Fall, Cluster oder alles)."""
    from engines.attack import map_result
    order = ["CLEAN", "LOW RISK", "ELEVATED", "HIGH RISK", "CRITICAL"]
    if cluster is not None and graph is not None:
        rows = [graph["files"][s] for s in cluster["files"]]
    else:
        rows = db.list_analyses(case_id=case_id, limit=100000)
    files, iocs, techniques, seen = [], {}, {}, set()
    for r in rows:
        if r["sha256"] in seen:
            continue
        seen.add(r["sha256"])
        if order.index(r.get("level") or "CLEAN") < order.index(min_level):
            continue
        files.append(r)
        for i in db.iocs_for(r["id"]):
            if i["type"] in RULE_TYPES + ("url",):
                iocs.setdefault((i["type"], i["value"].lower()), set()).add(r["name"])
        res = db.get_result(r["id"]) or {}
        for t in map_result(res)["techniques"]:
            if t["severity"] != "INFO":
                techniques[t["id"]] = t["name"]
    from core.iocgraph import _benign
    iocs = {k: v for k, v in iocs.items() if not (k[0] in ("domain", "email", "url") and _benign(k[1]))}
    return {"files": files, "iocs": iocs, "techniques": techniques}


_STIX_PATTERN = {
    "domain": "[domain-name:value = '{}']", "ipv4": "[ipv4-addr:value = '{}']",
    "email": "[email-addr:value = '{}']", "url": "[url:value = '{}']", "onion": "[domain-name:value = '{}']",
    "unc_path": "[file:parent_directory_ref.path = '{}']",
    "btc": "[x-crypto-wallet:address = '{}']", "xmr": "[x-crypto-wallet:address = '{}']",
}


def _sid(kind, value):
    return f"{kind}--{uuid.uuid5(_NS, kind + '|' + value)}"


def to_stix(data, title):
    now = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%S.000Z")
    ident = {"type": "identity", "spec_version": "2.1", "id": _sid("identity", APP_CODENAME),
             "created": now, "modified": now, "name": f"{APP_CODENAME} {APP_VERSION}", "identity_class": "system"}
    objs = [ident]

    def esc(v):
        return v.replace("\\", "\\\\").replace("'", "\\'")
    for (t, v), names in sorted(data["iocs"].items()):
        objs.append({"type": "indicator", "spec_version": "2.1", "id": _sid("indicator", f"{t}:{v}"),
                     "created": now, "modified": now, "created_by_ref": ident["id"], "name": f"{t}: {v}",
                     "description": "Seen in: " + ", ".join(sorted(names))[:500],
                     "indicator_types": ["malicious-activity"], "pattern_type": "stix",
                     "pattern": _STIX_PATTERN.get(t, "[x-ioc:value = '{}']").format(esc(v)), "valid_from": now})
    for f in data["files"]:
        objs.append({"type": "indicator", "spec_version": "2.1", "id": _sid("indicator", "sha256:" + f["sha256"]),
                     "created": now, "modified": now, "created_by_ref": ident["id"],
                     "name": f"file: {f['name']}", "description": f"{f.get('level')} {f.get('score')}/100 – "
                                                                   f"{f.get('headline') or ''}"[:500],
                     "indicator_types": ["malicious-activity"], "pattern_type": "stix",
                     "pattern": f"[file:hashes.'SHA-256' = '{f['sha256']}']", "valid_from": now})
    for tid, name in sorted(data["techniques"].items()):
        objs.append({"type": "attack-pattern", "spec_version": "2.1", "id": _sid("attack-pattern", tid),
                     "created": now, "modified": now, "name": name,
                     "external_references": [{"source_name": "mitre-attack", "external_id": tid,
                                              "url": "https://attack.mitre.org/techniques/" + tid.replace(".", "/") + "/"}]})
    refs = [o["id"] for o in objs[1:]]
    if refs:
        objs.append({"type": "report", "spec_version": "2.1", "id": _sid("report", title + now), "created": now,
                     "modified": now, "created_by_ref": ident["id"], "name": title, "published": now,
                     "report_types": ["threat-report"], "object_refs": refs})
    return {"type": "bundle", "id": _sid("bundle", title + now), "objects": objs}


_MISP_TYPE = {"domain": ("domain", "Network activity"), "ipv4": ("ip-dst", "Network activity"),
              "email": ("email-src", "Payload delivery"), "url": ("url", "Network activity"),
              "onion": ("domain", "Network activity"), "btc": ("btc", "Financial fraud"),
              "xmr": ("xmr", "Financial fraud"), "unc_path": ("filename", "Payload delivery")}


def to_misp(data, title, tlp="amber"):
    attrs = []
    for (t, v), names in sorted(data["iocs"].items()):
        typ, cat = _MISP_TYPE.get(t, ("text", "Other"))
        attrs.append({"type": typ, "category": cat, "value": v, "to_ids": True,
                      "comment": "Seen in: " + ", ".join(sorted(names))[:250]})
    for f in data["files"]:
        attrs.append({"type": "sha256", "category": "Payload delivery", "value": f["sha256"], "to_ids": True,
                      "comment": f"{f['name']} – {f.get('level')} {f.get('score')}/100"})
        attrs.append({"type": "filename", "category": "Payload delivery", "value": f["name"], "to_ids": False})
    tags = [{"name": f"tlp:{tlp}"}] + [{"name": f'misp-galaxy:mitre-attack-pattern="{n} - {tid}"'}
                                       for tid, n in sorted(data["techniques"].items())]
    worst = max((f.get("score") or 0 for f in data["files"]), default=0)
    return {"Event": {"info": title, "date": datetime.date.today().isoformat(),
                      "threat_level_id": "1" if worst >= 80 else "2" if worst >= 60 else "3",
                      "analysis": "2", "distribution": "0", "Attribute": attrs, "Tag": tags}}


def write_export(data, path, title):
    path = Path(path)
    suf = path.suffix.lower()
    if suf == ".csv":
        with open(path, "w", newline="", encoding="utf-8-sig") as fh:
            w = csv.writer(fh, delimiter=";")
            w.writerow(["type", "value", "seen_in"])
            for (t, v), names in sorted(data["iocs"].items()):
                w.writerow([_csv(t), _csv(v), _csv(", ".join(sorted(names)))])
            for f in data["files"]:
                w.writerow(["sha256", f["sha256"], _csv(f["name"])])
    elif path.name.lower().endswith(".misp.json"):
        path.write_text(json.dumps(to_misp(data, title), indent=2, ensure_ascii=False), encoding="utf-8")
    else:
        path.write_text(json.dumps(to_stix(data, title), indent=2, ensure_ascii=False), encoding="utf-8")
    return path


def _csv(v):
    s = str(v)
    return "'" + s if s[:1] in ("=", "+", "-", "@", "\t", "\r") else s
